[package]
name = "ruschess-app"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
notan = "0.11.0"
ruschess-core = { path = "../core" }
